service: 'ignitecertificate'

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local
custom:
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

  serverless-offline:
    httpPort: 3001
    babelOptions:
      presets: 
        - "env"
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true 

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  timeout: 10

functions:
  createTodo:
    handler: src/functions/createTodo.handle
    events:
      - http:
          path: /todos
          method: POST 
          cors: true
  listTodos:
    handler: src/functions/listTodos.handle
    events:
      - http:
          path: /todos
          method: GET
          cors: true

resources:
  Resources:
    todoApp:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todo 
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id 
            KeyType: HASH
          - AttributeName: id 
            KeyType: RANGE
